feat: create list event component
geo-event-tracker/event-tracker pull request #10
Opened 2022-02-17 13:27 UTC by ivan-ngchakming

Blocked by #9 

Closes #4

2022-02-17 20:20 UTC, toonvanvr commented on frontend/src/app/event-list/event-list.component.ts
> +  formatDate = (d: Date) => {
things like this should be moved to helper functions or libraries over time, but for the MVP we can clean these things out later

2022-02-17 20:20 UTC, toonvanvr commented on frontend/src/app/event-list/event-list.component.ts
> +    if (diff < 60) return `${diff.toFixed(0)} second${diff >= 2 ? 's' : ''}`;
!== 1

0 seconds
1 second
2 seconds

2022-02-17 20:40 UTC, toonvanvr commented on frontend/package.json
> +    "@angular/material": "^13.2.3",
Did you run `ng add @angular/material`? I created an example branch where that ran at [`demo/ng-add-angular-material`](https://github.com/geo-event-tracker/event-tracker/tree/demo/ng-add-angular-material). It modified more files

2022-02-19 11:04 UTC, toonvanvr commented on frontend/src/app/event-list/event-list.component.ts
> +    return `${coordinates.longitude} ${coordinates.latitude}`
I don't like this kind of writing so much. This is clearly an if/else statement and it takes longer to understand writing it in this shortened form.

I'd say:
```suggestion
return address ?? `${coordinates.longitude} ${coordinates.latitude}`
```
or a conditional statement, but there you repeat the word 'address'

2022-02-19 11:10 UTC, ivan-ngchakming commented on frontend/src/app/event-list/event-list.component.ts
> +    return `${coordinates.longitude} ${coordinates.latitude}`
Is this better?
```js
getAddress = ({ address, coordinates }: IGeoEvent) => {
  return address || `${coordinates.longitude} ${coordinates.latitude}`;
}
```

2022-02-19 11:37 UTC, toonvanvr commented on frontend/src/app/modules/data/model/interfaces/geo-event.interface.ts
> +  address: string
In your event service code, you treat address as optional value while it's required here?

That's a reason why you shouldn't use `props: any` in your `createMockGeoEvent`.

2022-02-19 11:50 UTC, toonvanvr commented on frontend/src/app/modules/data/services/geo-events.service.ts
> +})
```suggestion
const createMockGeoEvent = (props: Partial<IGeoEvent>): IGeoEvent => ({
  id: '0',
  coordinates: {
    latitude: 48.858093,
    longitude: 2.294694,
  },
  title: 'Start of construction of the Eiffel Tower',
  timestamp: new Date(2022, 1, 15, 20, 50),
  ...props,
})
```

Note: this will require you to set add `"exactOptionalPropertyTypes": true` to `tsconfig.json`.

2022-02-19 12:40 UTC, ivan-ngchakming commented on frontend/src/app/modules/data/model/interfaces/geo-event.interface.ts
> +  address: string
Ah yes I forgot about this any, my bad

2022-02-19 16:10 UTC, toonvanvr approved these changes

2022-02-19 16:10 UTC, toonvanvr commented on frontend/src/app/event-list/event-list.component.ts
> +  }
There's no need to set the observable during `ngOnInit` since you're not setting it back to null anywhere.

What you do handle in there are the subscriptions created from that observable.

```suggestion
  readonly geoEvents$ = this.geoEventsService.getAll();

  constructor(private readonly geoEventsService: GeoEventsService) { }
```

No need to add typing to the variable at this place imo. It keeps it more readable and if we make small functions for everything, it'll be typed checked at the first next step.

2022-02-19 16:10 UTC, toonvanvr commented on frontend/src/app/utils/datetime.ts
> +const getTimePassed = (timestamp: Date) => {
I'd suggest to use a library for time stuff later on and let helper functions call on that library. There are too many different cases and edge cases to write custom helper functions for everything date/time/period/offset/.. related.

2022-02-19 16:13 UTC, toonvanvr requested changes
See commit suggestion regarding the observable

2022-02-28 09:44 UTC, toonvanvr approved these changes
👍

2022-02-28 09:53 UTC, merged